In [1]:
import numpy as np 
import pandas as pd

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.svm import SVC
from sklearn. ensemble import RandomForestClassifier, BaggingClassifier, AdaBoostClassifier, VotingClassifier

In [2]:
data=pd.read_csv('breast-cancer.csv')
data.head()

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
0  ...          17.33           184.60      2019.0            0.1622   
1  ...          23.41           158.80      1956.0            0.1238   
2  ...          25.53           152.50      1709.0            0.1444   
3  ...          26.50            98.87       567.7            0.2098   
4  ...          16.67           152.20      1575.0            0.1374   

   compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
0             0.6656           0.7119                0.2654          0.4601   
1             0.1866           0.2416                0.1860          0.2750   
2             0.4245           0.4504                0.2430          0.3613   
3             0.8663           0.6869                0.2575          0.6638   
4             0.2050           0.4000                0.1625          0.2364   

   fractal_dimension_worst  Unnamed: 32  
0                  0.11890          NaN  
1                  0.08902          NaN  
2                  0.08758          NaN  
3                  0.17300          NaN  
4                  0.07678          NaN  

[5 rows x 33 columns]

In [3]:
data.shape

(569, 33)

In [4]:
data.isna().sum()

id                           0
diagnosis                    0
radius_mean                  0
texture_mean                 0
perimeter_mean               0
area_mean                    0
smoothness_mean              0
compactness_mean             0
concavity_mean               0
concave points_mean          0
symmetry_mean                0
fractal_dimension_mean       0
radius_se                    0
texture_se                   0
perimeter_se                 0
area_se                      0
smoothness_se                0
compactness_se               0
concavity_se                 0
concave points_se            0
symmetry_se                  0
fractal_dimension_se         0
radius_worst                 0
texture_worst                0
perimeter_worst              0
area_worst                   0
smoothness_worst             0
compactness_worst            0
concavity_worst              0
concave points_worst         0
symmetry_worst               0
fractal_dimension_worst      0
Unnamed:

In [5]:
###  Independent And dependent features
X = data.drop('diagnosis', axis=1)
y = data['diagnosis']

#### Zero Null Values

In [6]:
print(y.isnull().sum())

0


In [7]:
print(y.value_counts())

diagnosis
B    357
M    212
Name: count, dtype: int64


### Diagnosis (M = malignant, B = benign)
### Class distribution: 357 benign, 212 malignant

In [8]:
X=X.dropna(axis=1)

##### Splitting the data to train it in a model

In [9]:
x_train, x_test, y_train, y_test = train_test_split(X, y, test_size=0.30, random_state=4)

In [10]:
# scaling data

from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X_train = scaler.fit_transform(x_train)
X_test = scaler.transform(x_test)

In [11]:
# fitting data to model

from sklearn.linear_model import LogisticRegression

log_reg = LogisticRegression()
log_reg.fit(X_train, y_train)

LogisticRegression()

In [12]:
# model predictions

y_pred = log_reg.predict(X_test)

In [13]:
# accuracy score

from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

print(accuracy_score(y_train, log_reg.predict(X_train)))

log_reg_acc = accuracy_score(y_test, log_reg.predict(X_test))
print(log_reg_acc)

0.9874371859296482
0.9649122807017544


### Logistic Regression Accuracy = 96.4%

In [14]:
#descision tree
dt = DecisionTreeClassifier()
dt.fit(x_train,y_train)

DecisionTreeClassifier()

In [15]:
dt.score(x_train,y_train)

1.0

In [16]:
Des_Tree = dt.score(x_test,y_test)
Des_Tree

0.9122807017543859

In [17]:
y_pred=dt.predict(x_test)

In [18]:
from sklearn import metrics
print(metrics.confusion_matrix(y_test,y_pred))
print(metrics.classification_report(y_test,y_pred))

[[105  12]
 [  3  51]]
              precision    recall  f1-score   support

           B       0.97      0.90      0.93       117
           M       0.81      0.94      0.87        54

    accuracy                           0.91       171
   macro avg       0.89      0.92      0.90       171
weighted avg       0.92      0.91      0.91       171



In [19]:
#Random Forest - Ensemble of Descision Trees

rf = RandomForestClassifier(n_estimators=20)
rf.fit(x_train,y_train)

RandomForestClassifier(n_estimators=20)

In [20]:
ran_for = rf.score(x_test,y_test)
ran_for

0.9239766081871345

##### Accuracy of 94.7% from Random Classifier

### Bagging

In [21]:
#Bagging 

bg = BaggingClassifier(DecisionTreeClassifier(), max_samples= 0.5, max_features = 1.0, n_estimators = 20)
bg.fit(x_train,y_train)

BaggingClassifier(estimator=DecisionTreeClassifier(), max_samples=0.5,
                  n_estimators=20)

In [22]:
bg.score(x_test,y_test)

0.9181286549707602

#### Accuracy of 92.8% after bagging

### Boosting - Ada Boost

In [23]:
#Boosting - Ada Boost

adb = AdaBoostClassifier(DecisionTreeClassifier(),n_estimators = 5, learning_rate = 1)

adb.fit(x_train,y_train)
ada_acc = adb.score(x_test,y_test)
ada_acc


0.9064327485380117

#### Accuracy score of 88.8% from Ada Boost

### GradientBoostingClassifier

In [24]:
from sklearn.ensemble import GradientBoostingClassifier

clf = GradientBoostingClassifier(n_estimators=100, learning_rate=1.0, max_depth=1, random_state=0)

clf.fit(x_train, y_train)
clf.score(x_test, y_test)

0.9473684210526315

In [25]:
gdb_acc = adb.score(x_test,y_test)
gdb_acc

0.9064327485380117

#### Accuracy Score of 88.8% from Gradient Boost 

#### LightGBM is a fast, distributed, high performance gradient boosting framework based on decision tree algorithms, used for ranking, classification and many other machine learning tasks. It has helped Kagglers win data science competitions.

In [26]:
import lightgbm as lgb

In [27]:
clf = lgb.LGBMClassifier()
clf.fit(x_train, y_train)

[LightGBM] [Warning] Found whitespace in feature_names, replace with underlines
[LightGBM] [Info] Number of positive: 158, number of negative: 240
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.001059 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 4111
[LightGBM] [Info] Number of data points in the train set: 398, number of used features: 31
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.396985 -> initscore=-0.418044
[LightGBM] [Info] Start training from score -0.418044
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain

LGBMClassifier()

In [28]:
preds_class=clf.predict(x_test)

In [29]:
print(metrics.confusion_matrix(y_test,preds_class))
print(clf.score(x_test,y_test))

[[111   6]
 [  3  51]]
0.9473684210526315


### Stacked Generalization


#### Stacked generalization consists in stacking the output of individual estimator and use a classifier to compute the final prediction. Stacking allows to use the strength of each individual estimator by using their output as input of a final estimator.

In [30]:
estimators=[('lr', LogisticRegression(solver='lbfgs',   max_iter=1000)),
            ('dt', DecisionTreeClassifier()),
            ('svm', SVC(degree=2, kernel='poly'))]

In [31]:
from sklearn.svm import LinearSVC
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import make_pipeline
estimators = [('rf', RandomForestClassifier(n_estimators=10, random_state=42)),
              ('svr', make_pipeline(StandardScaler(),
                          LinearSVC(random_state=42)))]

In [32]:
from sklearn.ensemble import StackingClassifier
clf = StackingClassifier(estimators=estimators, final_estimator=LogisticRegression())


In [33]:
sgd_acc = clf.fit(x_train, y_train).score(x_test, y_test)
sgd_acc

C:\Users\Manikanta Mamidi\anaconda3\lib\site-packages\sklearn\svm\_classes.py:32: FutureWarning: The default value of `dual` will change from `True` to `'auto'` in 1.5. Set the value of `dual` explicitly to suppress the warning.
  warnings.warn(
C:\Users\Manikanta Mamidi\anaconda3\lib\site-packages\sklearn\svm\_classes.py:32: FutureWarning: The default value of `dual` will change from `True` to `'auto'` in 1.5. Set the value of `dual` explicitly to suppress the warning.
  warnings.warn(
C:\Users\Manikanta Mamidi\anaconda3\lib\site-packages\sklearn\svm\_classes.py:32: FutureWarning: The default value of `dual` will change from `True` to `'auto'` in 1.5. Set the value of `dual` explicitly to suppress the warning.
  warnings.warn(
C:\Users\Manikanta Mamidi\anaconda3\lib\site-packages\sklearn\svm\_classes.py:32: FutureWarning: The default value of `dual` will change from `True` to `'auto'` in 1.5. Set the value of `dual` explicitly to suppress the warning.
  warnings.warn(
C:\Users\Manikan

0.9649122807017544

#### Multiclass classification - XGB

In [34]:
import numpy as np
from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import GaussianNB
from sklearn.ensemble import RandomForestClassifier, VotingClassifier
clf1 = LogisticRegression(multi_class='multinomial', random_state=1)
clf2 = RandomForestClassifier(n_estimators=50, random_state=1)
clf3 = GaussianNB()
X = np.array([[-1, -1], [-2, -1], [-3, -2], [1, 1], [2, 1], [3, 2]])
y = np.array([1, 1, 1, 2, 2, 2])
eclf1 = VotingClassifier(estimators=[
        ('lr', clf1), ('rf', clf2), ('gnb', clf3)], voting='hard')
eclf1 = eclf1.fit(X, y)
print(eclf1.predict(X))
print(eclf1.score(X,y))

[1 1 1 2 2 2]
1.0


### XGB

In [35]:
from sklearn.datasets import load_breast_cancer, load_diabetes, load_wine
wine = load_wine()

from xgboost import XGBClassifier 

X = wine.data
y = wine.target

xgb = XGBClassifier(objective="multi:softprob", random_state=42)
xgb.fit(X, y)

y_pred = xgb.predict(X)

print(confusion_matrix(y, y_pred))
print(xgb.score(X,y_pred))

[[59  0  0]
 [ 0 71  0]
 [ 0  0 48]]
1.0


### Voting Classifier - Multiple Model Ensemble

In [36]:
# Voting Classifier - Multiple Model Ensemble 
from sklearn. ensemble import  VotingClassifier
lr = LogisticRegression(solver='lbfgs', max_iter=1400)
dt = DecisionTreeClassifier()
svm = SVC(kernel = 'poly', degree = 2 )

In [37]:
evc = VotingClassifier( estimators= [('logistic',lr),('dt',dt),('svm',svm)], voting = 'hard')

In [38]:
evc.fit(x_train,y_train)

VotingClassifier(estimators=[('logistic', LogisticRegression(max_iter=1400)),
                             ('dt', DecisionTreeClassifier()),
                             ('svm', SVC(degree=2, kernel='poly'))])

In [39]:
vc_acc = evc.score(x_test,y_test)
vc_acc

0.6842105263157895

### KNN 

In [40]:
from sklearn.neighbors import  KNeighborsClassifier

knn = KNeighborsClassifier()
knn.fit(x_train,y_train)

KNeighborsClassifier()

In [41]:
y_pred1 = knn.predict(x_test)

In [42]:
y_pred1

array(['B', 'B', 'B', 'M', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B',
       'B', 'M', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'M', 'M', 'B', 'B',
       'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'M', 'B',
       'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'M', 'B', 'M', 'M', 'B',
       'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B',
       'B', 'B', 'B', 'B', 'M', 'B', 'B', 'B', 'M', 'B', 'M', 'M', 'B',
       'B', 'B', 'B', 'M', 'B', 'M', 'B', 'B', 'B', 'M', 'B', 'B', 'B',
       'B', 'B', 'M', 'B', 'B', 'M', 'B', 'B', 'B', 'B', 'M', 'M', 'B',
       'B', 'B', 'B', 'M', 'B', 'M', 'B', 'M', 'B', 'B', 'B', 'B', 'B',
       'B', 'M', 'B', 'B', 'B', 'M', 'B', 'B', 'B', 'B', 'M', 'B', 'B',
       'B', 'B', 'M', 'B', 'B', 'M', 'M', 'M', 'B', 'M', 'M', 'B', 'B',
       'B', 'M', 'M', 'B', 'B', 'B', 'M', 'B', 'M', 'M', 'B', 'B', 'B',
       'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'M',
       'B', 'B'], dtype=object)

In [43]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
print(accuracy_score(y_train, knn.predict(x_train)))
knn_acc = accuracy_score(y_test, knn.predict(x_test))
print(knn_acc)
y_pred2 = knn.predict(x_test)
print(confusion_matrix(y_test, y_pred2))
print(classification_report(y_test, y_pred2))

0.8316582914572864
0.7602339181286549
[[105  12]
 [ 29  25]]
              precision    recall  f1-score   support

           B       0.78      0.90      0.84       117
           M       0.68      0.46      0.55        54

    accuracy                           0.76       171
   macro avg       0.73      0.68      0.69       171
weighted avg       0.75      0.76      0.75       171



### SVM

In [44]:
# hyperparamter tuning
from sklearn.svm import SVC
from sklearn.model_selection import GridSearchCV
svc = SVC(probability=True)
params = {
    'gamma':[0.0001,0.002,0.001,0.01,0.1],
    'C':[0.01,0.05,0.5,0.1,1,1.11,14,20,15]
}

grid_search = GridSearchCV(svc, params)
grid_search.fit(x_train,y_train)

GridSearchCV(estimator=SVC(probability=True),
             param_grid={'C': [0.01, 0.05, 0.5, 0.1, 1, 1.11, 14, 20, 15],
                         'gamma': [0.0001, 0.002, 0.001, 0.01, 0.1]})

In [45]:
grid_search.best_params_

{'C': 1, 'gamma': 0.0001}

In [46]:
grid_search.best_score_

0.6080696202531646

In [47]:
svc = SVC(C=14, gamma=0.01, probability=True)
svc.fit(x_train,y_train)

SVC(C=14, gamma=0.01, probability=True)

In [48]:
Y_pred = svc.predict(x_test)
Y_pred

array(['B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B',
       'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B',
       'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B',
       'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B',
       'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B',
       'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B',
       'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B',
       'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B',
       'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B',
       'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B',
       'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B',
       'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B',
       'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B',
       'B', 'B'], dtype=object)

In [49]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
print(accuracy_score(y_train, svc.predict(x_train)))
svc_acc = accuracy_score(y_test, svc.predict(x_test))
print(svc_acc)
Y_pred = svc.predict(x_test)
print(confusion_matrix(y_test, Y_pred))
print(classification_report(y_test, Y_pred))

1.0
0.6842105263157895
[[117   0]
 [ 54   0]]
              precision    recall  f1-score   support

           B       0.68      1.00      0.81       117
           M       0.00      0.00      0.00        54

    accuracy                           0.68       171
   macro avg       0.34      0.50      0.41       171
weighted avg       0.47      0.68      0.56       171



C:\Users\Manikanta Mamidi\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\Manikanta Mamidi\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\Manikanta Mamidi\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [50]:
models = pd.DataFrame({
    'Model': ['Logistic Regression', 'KNN', 'SVC', 'SGD Classifier', 'Decision Tree Classifier', 'Random Forest Classifier', 'Voting Classifier', 'Ada Boost Classifier',
             'Gradient Boosting Classifier'],
    'Score': [log_reg_acc, knn_acc, svc_acc, sgd_acc, Des_Tree, ran_for, vc_acc, ada_acc, gdb_acc]
})

models.sort_values(by = 'Score', ascending = False)

Model     Score
0           Logistic Regression  0.964912
3                SGD Classifier  0.964912
5      Random Forest Classifier  0.923977
4      Decision Tree Classifier  0.912281
7          Ada Boost Classifier  0.906433
8  Gradient Boosting Classifier  0.906433
1                           KNN  0.760234
2                           SVC  0.684211
6             Voting Classifier  0.684211

## Best model for diagnosing breast cancer is "Logistic Regression" and "SGD Classifier" with an accuracy of 96.4%.